
<div class="container" data-ng-controller="CustomerCtrl as cCtrl" ng-init="getCustomer()">
    <div class="block-header p-l-0" style="margin-right: -12px;">
        <h2><b>Settings > Customer</b></h2>

        <ul class="actions">
            <li>
                <div class="form-group">
                    <div class="fg-line">
                        <input type="text" placeholder="Search" ng-change="getCustomer()" ng-model="customer_search" class="input-sm form-control seach-module" maxlength="50">
                    </div>
                </div>
            </li>
            <li title="Refresh">
                <a href="" data-ng-click="getCustomer(); "><i class="zmdi zmdi-refresh" ></i></a>
            </li>
        </ul>
    </div>

    <div class="card">
        <a  title="Add New" class="btn btn-float m-btn ng-scope waves-effect waves-circle" href="" ng-click="addCustomerForm();" data-current-skin={{uxctrl.currentSkin}}><i class="zmdi zmdi-plus"></i></a>
        <div class="card-body table-responsive">
            <table ng-table="customerTable" class="table table-display-inline table-striped table-vmiddle">
                <thead>
                    <tr>
                        <th></th>
                        <th> CUSTOMER NAME </th>
                        <th> CREATED BY </th>
                    </tr>
                </thead>
                <!-- <tr ng-repeat="list in users | orderBy: 'complete_name'"> -->
                <tr ng-repeat="list in customerList">
                    <td width="10%">
                        <div class="p-t-5" ng-style="{width : '80px'}">
                            <span>
                                <ul class="actions" data-ng-if="!list.$edit">
                                    <li>
                                        <!-- <a title="Edit" data-ng-click="onEditSpecific(list);"> -->
                                        <a ng-if="userRole.access.edit" title="Edit" data-ng-click="editCustomerForm(list);">
                                            <i class="zmdi zmdi-edit"></i>
                                        </a>
                                        <a ng-if="userRole.access.delete" title="Delete" data-ng-click="onDeleteCustomer(list.key)">
                                            <i class="zmdi zmdi-delete"></i>
                                        </a>
                                    </li>
                                </ul>
                            </span>
                        </div>

                    </td>

                    <td>
                        <div class="p-t-2" ng-style="{width:'100%'}">
                            {{ list.fullname }}
                        </div>
                    </td>
                    <td>
                        <div class="p-t-2" ng-style="{width:'100%'}">
                            <i class="zmdi zmdi-account"></i> {{ list.created_by }} <br>
                            <i class="zmdi zmdi-calendar"></i> {{ list.created_at }}
                        </div>
                    </td>
                </tr>
                <tr ng-if="customerList.length == 0">
                    <td colspan="3" ><center>No record(s) found</center></td>
                </tr>
            </table>
        </div>
    
    </div>

    <script type="text/ng-template" id="addCustomerForm">
        <div class="modal-header p-b-15">
            <i class="close zmdi zmdi-close zmdi-hc-fw" ng-click="clearFields();cancel();"></i>
            <h2 class="text-center">ADD CUSTOMER</h2>
        </div>
        <div class="modal-body p-b-0 " style="padding:0 25% 0; height:auto;">
            <div class="row p-l-25" style="width:100%">
                <div class="form-group p-l-15" style="width:100%">
                    All fields with <span class="c-red">*</span> are required
                </div>
                <div class="col-sm-4 m-b-10">
                    <div class="form-group m-b-5">
                        <div id="completeNameContainer" class="fg-line">
                            <label style="z-index:1024;">First Name
                                <span class="c-red">*</span>
                            </label>
                             <input id="f_name" class="form-control bgm-white p-l-5" type="text" ng-model="customer.f_name" maxlength="50" placeholder="First Name"
                             />
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 m-b-10">
                    <div class="form-group m-b-5">
                        <div id="completeNameContainer" class="fg-line">
                            <label style="z-index:1024;">Last Name
                                <span class="c-red">*</span>
                            </label>
                             <input id="l_name" class="form-control bgm-white p-l-5" type="text" ng-model="customer.l_name" maxlength="50" placeholder="Last Name"
                             />
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 m-b-10">
                    <div class="form-group m-b-5">
                        <div id="completeNameContainer" class="fg-line">
                            <label style="z-index:1024;">Middle Name
                            </label>
                             <input id="m_name" class="form-control bgm-white p-l-5" type="text" ng-model="customer.m_name" maxlength="50" placeholder="Middle Name"
                             />
                        </div>
                    </div>
                </div>
            </div>
              <div class="p-l-25 row">
                <div class="col-sm-12 m-b-10 p-5">
                    <button type="button" style="width: 98%;" class="btn btn-primary btn-block p-t-10 p-b-10" ng-click="addNewCustomer();">
                        Add Entry
                    </button>
                </div>
             </div>
        </div>
        <div class="modal-footer p-t-0 p-l-25 p-r-30">

        </div>
    </script>

    <script type="text/ng-template" id="editCustomerForm">
        <div class="modal-header p-b-15">
            <i class="close zmdi zmdi-close zmdi-hc-fw" ng-click="clearFields();cancel();"></i>
            <h2 class="text-center">EDIT CUSTOMER</h2>
        </div>
        <div class="modal-body p-b-0 " style="padding:0 25% 0; height:auto;">
            <div class="row p-l-25" style="width:100%">
                <div class="form-group p-l-15" style="width:100%">
                    All fields with <span class="c-red">*</span> are required
                </div>
                <div class="col-sm-4 m-b-10">
                    <div class="form-group m-b-5">
                        <div id="completeNameContainer" class="fg-line">
                            <label style="z-index:1024;">First Name
                                <span class="c-red">*</span>
                            </label>
                             <input id="f_name" class="form-control bgm-white p-l-5" type="text" ng-model="customer.edit_f_name" maxlength="50" placeholder="First Name"
                             />
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 m-b-10">
                    <div class="form-group m-b-5">
                        <div id="completeNameContainer" class="fg-line">
                            <label style="z-index:1024;">Last Name
                                <span class="c-red">*</span>
                            </label>
                             <input id="l_name" class="form-control bgm-white p-l-5" type="text" ng-model="customer.edit_l_name" maxlength="50" placeholder="Last Name"
                             />
                        </div>
                    </div>
                </div>
                <div class="col-sm-4 m-b-10">
                    <div class="form-group m-b-5">
                        <div id="completeNameContainer" class="fg-line">
                            <label style="z-index:1024;">Middle Name
                            </label>
                             <input id="m_name" class="form-control bgm-white p-l-5" type="text" ng-model="customer.edit_m_name" maxlength="50" placeholder="Middle Name"
                             />
                        </div>
                    </div>
                </div>
            </div>
              <div class="p-l-25 row">
                <div class="col-sm-12 m-b-10 p-5">
                    <button type="button" style="width: 98%;" class="btn btn-primary btn-block p-t-10 p-b-10" ng-click="updateCustomer();">
                        Update
                    </button>
                </div>
             </div>
        </div>
        <div class="modal-footer p-t-0 p-l-25 p-r-30">

        </div>
    </script>
</div>